# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20170205_0259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='author',
            new_name='auth',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='degree',
            field=models.CharField(max_length=150, verbose_name='degree'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=60, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='mobile_number',
            field=models.CharField(max_length=25, verbose_name='mobile number'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='school',
            field=models.CharField(max_length=150, verbose_name='school'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telephone_number',
            field=models.CharField(max_length=25, verbose_name='telephone number'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_name',
            field=models.EmailField(max_length=60, verbose_name='user name'),
        ),
    ]
