# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 19:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20170205_0312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='auth',
        ),
    ]
