# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 10:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_title', models.CharField(default='no portfolio name', max_length=255)),
                ('number_of_projects', models.IntegerField()),
                ('portfolio_type', models.CharField(max_length=127, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(default='no project name', max_length=255)),
                ('project_description', models.CharField(max_length=500, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_file', models.FileField(blank=True, upload_to='accounts/projects/')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='QuiverMain.Project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPortfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuiverMain.Portfolio')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuiverMain.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(default='no tags', max_length=100)),
                ('tags', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='QuiverMain.Project')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=127, null=True, verbose_name='school')),
                ('degree', models.CharField(max_length=127, null=True, verbose_name='degree')),
                ('address', models.CharField(max_length=255, null=True, verbose_name='address')),
                ('mobile_number', models.CharField(max_length=12, null=True, verbose_name='mobile number')),
                ('telephone_number', models.CharField(max_length=12, null=True, verbose_name='telephone number')),
                ('birth_date', models.DateTimeField(null=True, verbose_name='birthday')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True, verbose_name='gender')),
                ('bio', models.CharField(max_length=500, null=True, verbose_name='biography')),
                ('profile_picture', models.ImageField(blank=True, upload_to='accounts/avatar/', verbose_name='profile_picture')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuiverMain.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
