# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 10:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuiverMain', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tags',
            new_name='project',
        ),
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
    ]
