# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuiverMain', '0002_auto_20170224_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
