# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuiverMain', '0003_auto_20170307_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
