# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuiverMain', '0004_auto_20170307_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(max_length=254, null=True, verbose_name='address'),
        ),
    ]
