# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuiverMain', '0005_auto_20170308_0550'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='alternative_email',
            field=models.EmailField(max_length=254, null=True, verbose_name='alternative_email'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='website',
            field=models.CharField(max_length=254, null=True, verbose_name='website'),
        ),
    ]
