# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schematicsapp', '0002_auto_20170215_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='schematicmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='schematicmodel',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
